### ISSUE TITLE
npm WARN deprecated crypto@1.0.1

### ISSUE THREAD

**Issue by midnight-wonderer** [MiguelSavignano/node-credentials#48]
Hey
Are you still there?
npm warn about the deprecated package.

~~~
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
~~~

Should it be switched to the built-in package, as suggested?

**Comment by MiguelSavignano** [comment]
Hello, thanks for the issue. 
What Nodejs version did you use?
I will review if this warning depends on the Nodejs version; I'm not sure if old Nodejs versions support that.

**Comment by MiguelSavignano** [comment]
Tested with Nodejs version 10, 12, 14, 16, 18 and works.
